<?php
/**
 * Log Events constants class.
 *
 * @package Safe_Publish
 */

declare(strict_types=1);

namespace Safe_Publish\Utils;

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Central registry of log event codes referenced by the per-event helper
 * methods on each channel logger (Auth_Logger, Export_Logger, Content_Logger,
 * Media_Logger, Import_Logger). The constants here are the contract; the
 * helpers enforce the payload shape per event.
 */
class Log_Events {
	// Media import events.
	const FEATURED_IMAGE_FETCH_FAILED   = 'FEATURED_IMAGE_FETCH_FAILED';
	const FEATURED_IMAGE_MISSING_SOURCE = 'FEATURED_IMAGE_MISSING_SOURCE';
	const INVALID_ATTACHMENT_ID         = 'INVALID_ATTACHMENT_ID';
	const MEDIA_DOWNLOAD_FAILED         = 'MEDIA_DOWNLOAD_FAILED';
	const MEDIA_IMPORT_FAILED           = 'MEDIA_IMPORT_FAILED';
	const MEDIA_SIDELOAD_FAILED         = 'MEDIA_SIDELOAD_FAILED';
	const MEDIA_UNSUPPORTED_FILE_TYPE   = 'MEDIA_UNSUPPORTED_FILE_TYPE';

	// Content fetch events.
	const CONTENT_FETCH_FAILED           = 'CONTENT_FETCH_FAILED';
	const CONTENT_FETCH_INVALID_RESPONSE = 'CONTENT_FETCH_INVALID_RESPONSE';
	const CONTENT_FETCH_RAW_UNAVAILABLE  = 'CONTENT_FETCH_RAW_UNAVAILABLE';

	// Auth events.
	const NO_SECRET_CONFIGURED        = 'NO_SECRET_CONFIGURED';
	const TIMESTAMP_EXPIRED           = 'TIMESTAMP_EXPIRED';
	const CONTENT_HASH_MISSING        = 'CONTENT_HASH_MISSING';
	const CONTENT_HASH_MISMATCH       = 'CONTENT_HASH_MISMATCH';
	const NO_CONNECTED_URL_CONFIGURED = 'NO_CONNECTED_URL_CONFIGURED';
	const SITE_URL_HEADER_MISSING     = 'SITE_URL_HEADER_MISSING';
	const SITE_URL_MISMATCH           = 'SITE_URL_MISMATCH';
	const SIGNATURE_INVALID           = 'SIGNATURE_INVALID';
	const AUTH_SUCCESS                = 'AUTH_SUCCESS';

	// Permission and auth diagnostic events.
	const CAPABILITY_BASED_AUTH_SETUP    = 'CAPABILITY_BASED_AUTH_SETUP';
	const PERMISSION_CHECK_INTERCEPTED   = 'PERMISSION_CHECK_INTERCEPTED';
	const META_CAP_OVERRIDE              = 'META_CAP_OVERRIDE';
	const PERMISSION_OVERRIDE_APPLIED    = 'PERMISSION_OVERRIDE_APPLIED';
	const PERMISSION_CALLBACK_OVERRIDDEN = 'PERMISSION_CALLBACK_OVERRIDDEN';
	const COLLECTION_PARAMS_OVERRIDDEN   = 'COLLECTION_PARAMS_OVERRIDDEN';
	const CONTEXT_ERROR_OVERRIDDEN       = 'CONTEXT_ERROR_OVERRIDDEN';
	const EDIT_CONTEXT_ALLOWED           = 'EDIT_CONTEXT_ALLOWED';
	const PERMISSION_ERROR_INTERCEPTED   = 'PERMISSION_ERROR_INTERCEPTED';
	const LOGS_CLEARED                   = 'LOGS_CLEARED';
	const TEST_ENDPOINT_ACCESSED         = 'TEST_ENDPOINT_ACCESSED';

	// Export events.
	const CONTENT_EXPORTED     = 'CONTENT_EXPORTED';
	const EXPORT_REQUEST_ERROR = 'EXPORT_REQUEST_ERROR';
	const EXPORT_BAD_STATUS    = 'EXPORT_BAD_STATUS';

	// Import session and item lifecycle events.
	const SESSION_ROLLED_BACK     = 'SESSION_ROLLED_BACK';
	const ITEM_ROLLED_BACK        = 'ITEM_ROLLED_BACK';
	const SESSION_ROLLBACK_NOOP   = 'SESSION_ROLLBACK_NOOP';
	const ITEM_ROLLBACK_NOOP      = 'ITEM_ROLLBACK_NOOP';
	const SESSION_ROLLBACK_FAILED = 'SESSION_ROLLBACK_FAILED';
	const ITEM_ROLLBACK_FAILED    = 'ITEM_ROLLBACK_FAILED';
	const SESSION_DELETED         = 'SESSION_DELETED';
	const SESSION_DELETE_FAILED   = 'SESSION_DELETE_FAILED';

	// Security-relevant settings change events.
	const SETTINGS_CONNECTED_SITE_URL_CHANGED  = 'SETTINGS_CONNECTED_SITE_URL_CHANGED';
	const SETTINGS_BASIC_AUTH_USERNAME_CHANGED = 'SETTINGS_BASIC_AUTH_USERNAME_CHANGED';
	const SETTINGS_BASIC_AUTH_PASSWORD_CHANGED = 'SETTINGS_BASIC_AUTH_PASSWORD_CHANGED';
	const SETTINGS_SYNC_MODE_CHANGED           = 'SETTINGS_SYNC_MODE_CHANGED';
}
