<?php
/**
 * Source/destination post parity asserter for integration tests.
 *
 * @package Safe_Publish
 */

declare(strict_types=1);

namespace Safe_Publish\Tests\Integration;

use PHPUnit\Framework\TestCase;
use WP_Post;

/**
 * Schema-driven asserter for source-to-destination post parity.
 *
 * Models every wp_posts column explicitly: each column is either checked for
 * equality, listed in the divergence registry with a reason it must differ,
 * or listed as deferred (covered in a later test phase). The
 * assert_no_unmodeled_columns() check fails loudly if a column ever appears
 * outside these three categories — so adding a wp_posts column (e.g. a future
 * WordPress release) or omitting one from the rules surfaces as a test
 * failure rather than silent skipping.
 */
final class Post_Parity_Asserter {

	/**
	 * Canonical list of wp_posts columns the asserter classifies.
	 *
	 * Updated when WordPress changes the schema. Each column must appear in
	 * exactly one of: identity / content / status / timing / misc rules, the
	 * divergence registry, or the deferred registry.
	 *
	 * @var list<string>
	 */
	private const WP_POSTS_COLUMNS = array(
		'ID',
		'post_author',
		'post_date',
		'post_date_gmt',
		'post_content',
		'post_title',
		'post_excerpt',
		'post_status',
		'comment_status',
		'ping_status',
		'post_password',
		'post_name',
		'to_ping',
		'pinged',
		'post_modified',
		'post_modified_gmt',
		'post_content_filtered',
		'post_parent',
		'guid',
		'menu_order',
		'post_type',
		'post_mime_type',
		'comment_count',
	);

	/**
	 * Identity-style columns: post_type, slug.
	 *
	 * Source REST field => wp_posts column.
	 *
	 * @var array<string, string>
	 */
	private const IDENTITY_COLUMNS = array(
		'type' => 'post_type',
		'slug' => 'post_name',
	);

	/**
	 * Content-style columns checked for parity. post_content is deferred —
	 * see DEFERRED_REGISTRY.
	 *
	 * Source REST field => wp_posts column. Title/excerpt come as
	 * `[ 'raw' => string ]` and need .raw unwrapping (see lookup helper).
	 *
	 * @var array<string, string>
	 */
	private const CONTENT_COLUMNS = array(
		'title'   => 'post_title',
		'excerpt' => 'post_excerpt',
	);

	/**
	 * Status-style columns checked for parity.
	 *
	 * Source REST field => wp_posts column. post_status diverges by design
	 * (see DIVERGENCE_REGISTRY) so it's not in this mapping.
	 *
	 * @var array<string, string>
	 */
	private const STATUS_COLUMNS = array(
		'comment_status' => 'comment_status',
		'ping_status'    => 'ping_status',
		'password'       => 'post_password',
	);

	/**
	 * Misc columns checked for parity.
	 *
	 * Source REST field => wp_posts column. Columns whose source value is
	 * always the WP default (to_ping, pinged, post_content_filtered) are
	 * checked against the empty default; comment_count is always 0 because
	 * comments aren't migrated.
	 *
	 * @var array<string, string>
	 */
	private const MISC_COLUMNS = array(
		'menu_order' => 'menu_order',
	);

	/**
	 * Columns whose source value isn't part of the REST body but whose dest
	 * value is expected to be the WordPress default. Checked against the
	 * provided default string.
	 *
	 * @var array<string, string>
	 */
	private const DEFAULT_VALUE_COLUMNS = array(
		'to_ping'               => '',
		'pinged'                => '',
		'post_content_filtered' => '',
		'post_mime_type'        => '',
		'comment_count'         => '0',
	);

	/**
	 * Columns expected to differ between source and dest. Skipped during
	 * parity checks; the reason is documented for reviewers.
	 *
	 * @var array<string, string>
	 */
	private const DIVERGENCE_REGISTRY = array(
		'ID'                => 'namespace difference (source vs dest WordPress)',
		'post_status'       => 'imported as draft for manual review; source status not propagated',
		'post_date'         => 'set to import time, source publish date not propagated',
		'post_date_gmt'     => 'left as 0000-00-00 00:00:00 for drafts; WordPress sets it at publish time',
		'post_modified'     => 'set to import time, not source modified time',
		'post_modified_gmt' => 'set to import time, not source modified time',
		'guid'              => 'regenerated by dest WordPress, source GUID not propagated',
	);

	/**
	 * Columns whose parity check is deferred to a later test phase. Each
	 * entry names the phase that will cover it.
	 *
	 * @var array<string, string>
	 */
	private const DEFERRED_REGISTRY = array(
		'post_content' => 'deferred: URL/ID rewriting parity (later phase)',
		'post_author'  => 'deferred: author resolution semantics (later phase)',
		'post_parent'  => 'deferred: hierarchical post support not in seeder yet',
	);

	/**
	 * Asserts parity for identity-style columns (type, slug).
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_identity_columns(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		self::assert_mapped_columns(
			self::IDENTITY_COLUMNS,
			$source_body,
			$dest_post,
			$test
		);
	}

	/**
	 * Asserts parity for content-style columns (title, excerpt).
	 *
	 * Note: post_content is intentionally NOT checked here — see
	 * DEFERRED_REGISTRY.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_content_columns(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		self::assert_mapped_columns(
			self::CONTENT_COLUMNS,
			$source_body,
			$dest_post,
			$test
		);
	}

	/**
	 * Asserts parity for status-style columns.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_status_columns(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		self::assert_mapped_columns(
			self::STATUS_COLUMNS,
			$source_body,
			$dest_post,
			$test
		);
	}

	/**
	 * Asserts miscellaneous column parity (menu_order) and that columns with
	 * no REST-side value land on the WordPress default on the dest.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_misc_columns(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		self::assert_mapped_columns(
			self::MISC_COLUMNS,
			$source_body,
			$dest_post,
			$test
		);

		$dest_array = $dest_post->to_array();

		foreach ( self::DEFAULT_VALUE_COLUMNS as $column => $expected_default ) {
			$test->assertSame(
				$expected_default,
				(string) ( $dest_array[ $column ] ?? '' ),
				"wp_posts column '{$column}' should be the WP default '{$expected_default}'"
			);
		}
	}

	/**
	 * Asserts that every wp_posts column is classified (parity rule,
	 * divergence registry, or deferred registry). Fails loudly when a column
	 * is unmodeled so adding columns or omitting them from the rules
	 * surfaces visibly instead of being silently skipped.
	 *
	 * @param TestCase $test Active test case.
	 */
	public static function assert_no_unmodeled_columns( TestCase $test ): void {
		$classified = array_merge(
			array_values( self::IDENTITY_COLUMNS ),
			array_values( self::CONTENT_COLUMNS ),
			array_values( self::STATUS_COLUMNS ),
			array_values( self::MISC_COLUMNS ),
			array_keys( self::DEFAULT_VALUE_COLUMNS ),
			array_keys( self::DIVERGENCE_REGISTRY ),
			array_keys( self::DEFERRED_REGISTRY )
		);

		$unmodeled = array_values(
			array_diff( self::WP_POSTS_COLUMNS, $classified )
		);

		$test->assertSame(
			array(),
			$unmodeled,
			'Every wp_posts column must be classified; unmodeled columns: '
			. implode( ', ', $unmodeled )
		);
	}

	/**
	 * Applies assertSame across a source-field => column mapping.
	 *
	 * Handles `[ 'raw' => string ]` REST wrappers transparently and falls
	 * back to the raw scalar when the field isn't wrapped.
	 *
	 * @param array<string, string> $mapping     Source field => wp_posts column.
	 * @param array<string, mixed>  $source_body Source REST response body.
	 * @param WP_Post               $dest_post   Imported destination post.
	 * @param TestCase              $test        Active test case.
	 */
	private static function assert_mapped_columns(
		array $mapping,
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		$dest_array = $dest_post->to_array();

		foreach ( $mapping as $source_field => $column ) {
			$source_value = self::source_value( $source_body, $source_field );
			$dest_value   = $dest_array[ $column ] ?? null;

			$test->assertSame(
				$source_value,
				$dest_value,
				"wp_posts column '{$column}' should match source"
				. " field '{$source_field}'"
			);
		}
	}

	/**
	 * Reads a source REST body field, unwrapping `[ 'raw' => ... ]` wrappers.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param string               $field       Top-level field name.
	 * @return mixed Raw field value.
	 */
	private static function source_value( array $source_body, string $field ): mixed {
		$value = $source_body[ $field ] ?? null;

		if ( is_array( $value ) && array_key_exists( 'raw', $value ) ) {
			return $value['raw'];
		}

		return $value;
	}
}
