<?php
/**
 * Source/destination post parity asserter for integration tests.
 *
 * @package Safe_Publish
 */

declare(strict_types=1);

namespace Safe_Publish\Tests\Integration;

use PHPUnit\Framework\TestCase;
use Safe_Publish\Utils\Options;
use WP_Error;
use WP_Post;

/**
 * Schema-driven asserter for source-to-destination post parity.
 *
 * Models every wp_posts column, every dest meta key, every term assignment,
 * and every sideloaded-attachment field explicitly: each is either checked
 * for parity, delegated to Content_Parity_Comparator for URL/ID-aware
 * checks, listed in a divergence / plugin-added registry with the documented
 * reason, or listed as deferred (covered in a later test phase). The
 * assert_no_unmodeled_* checks fail loudly if a column, meta key, or term
 * assignment ever appears outside these categories — so a future schema
 * change or import-pipeline tweak surfaces as a test failure rather than
 * silent skipping.
 */
final class Post_Parity_Asserter {

	/**
	 * Canonical list of wp_posts columns the asserter classifies.
	 *
	 * Updated when WordPress changes the schema. Each column must appear in
	 * exactly one of: identity / content / status / misc rules, the content
	 * body comparator bucket, the divergence registry, or the deferred
	 * registry.
	 *
	 * @var list<string>
	 */
	private const WP_POSTS_COLUMNS = array(
		'ID',
		'post_author',
		'post_date',
		'post_date_gmt',
		'post_content',
		'post_title',
		'post_excerpt',
		'post_status',
		'comment_status',
		'ping_status',
		'post_password',
		'post_name',
		'to_ping',
		'pinged',
		'post_modified',
		'post_modified_gmt',
		'post_content_filtered',
		'post_parent',
		'guid',
		'menu_order',
		'post_type',
		'post_mime_type',
		'comment_count',
	);

	/**
	 * Identity-style columns: post_type, slug.
	 *
	 * Source REST field => wp_posts column.
	 *
	 * @var array<string, string>
	 */
	private const IDENTITY_COLUMNS = array(
		'type' => 'post_type',
		'slug' => 'post_name',
	);

	/**
	 * Content-style columns checked for parity. post_content lives in
	 * CONTENT_BODY_COLUMNS and is checked via Content_Parity_Comparator.
	 *
	 * Source REST field => wp_posts column. Title/excerpt come as
	 * `[ 'raw' => string ]` and need .raw unwrapping (see lookup helper).
	 *
	 * @var array<string, string>
	 */
	private const CONTENT_COLUMNS = array(
		'title'   => 'post_title',
		'excerpt' => 'post_excerpt',
	);

	/**
	 * Status-style columns checked for parity.
	 *
	 * Source REST field => wp_posts column. post_status diverges by design
	 * (see DIVERGENCE_REGISTRY) so it's not in this mapping.
	 *
	 * @var array<string, string>
	 */
	private const STATUS_COLUMNS = array(
		'comment_status' => 'comment_status',
		'ping_status'    => 'ping_status',
		'password'       => 'post_password',
	);

	/**
	 * Misc columns checked for parity.
	 *
	 * Source REST field => wp_posts column. Columns whose source value is
	 * always the WP default (to_ping, pinged, post_content_filtered) are
	 * checked against the empty default; comment_count is always 0 because
	 * comments aren't migrated.
	 *
	 * @var array<string, string>
	 */
	private const MISC_COLUMNS = array(
		'menu_order' => 'menu_order',
	);

	/**
	 * Columns whose source value isn't part of the REST body but whose dest
	 * value is expected to be the WordPress default. Checked against the
	 * provided default string.
	 *
	 * @var array<string, string>
	 */
	private const DEFAULT_VALUE_COLUMNS = array(
		'to_ping'               => '',
		'pinged'                => '',
		'post_content_filtered' => '',
		'post_mime_type'        => '',
		'comment_count'         => '0',
	);

	/**
	 * Columns expected to differ between source and dest. Skipped during
	 * parity checks; the reason is documented for reviewers.
	 *
	 * @var array<string, string>
	 */
	private const DIVERGENCE_REGISTRY = array(
		'ID'                => 'namespace difference (source vs dest WordPress)',
		'post_status'       => 'imported as draft regardless of source status',
		'post_date'         => 'set to import time, source publish date not propagated',
		'post_date_gmt'     => 'WordPress stores 0000-00-00 00:00:00 for drafts',
		'post_modified'     => 'set to import time, not source modified time',
		'post_modified_gmt' => 'set to import time, not source modified time',
		'guid'              => 'regenerated by dest WordPress, source GUID not propagated',
	);

	/**
	 * Columns delegated to Content_Parity_Comparator because direct equality
	 * isn't meaningful after URL/ID rewriting.
	 *
	 * @var array<string, string>
	 */
	private const CONTENT_BODY_COLUMNS = array(
		'post_content' => 'URL/ID rewritten; Content_Parity_Comparator checks parity',
	);

	/**
	 * Columns whose parity check is deferred to a later test phase. Each
	 * entry names the phase that will cover it.
	 *
	 * @var array<string, string>
	 */
	private const DEFERRED_REGISTRY = array(
		'post_author' => 'deferred: author resolution semantics (later phase)',
		'post_parent' => 'deferred: hierarchical post support not in seeder yet',
	);

	/**
	 * Plugin-added meta keys the importer writes when importing a post. The
	 * expected value per post is computed in assert_plugin_added_meta() — this
	 * map only documents what each key means so reviewers can audit the set.
	 *
	 * Entries are written unconditionally and value-checked strictly, except
	 * _thumbnail_id, which is written only when the source had a
	 * featured_media (its dynamic dest attachment ID is checked for
	 * resolution rather than value-equality — see
	 * assert_thumbnail_id_for_source()).
	 *
	 * @var array<string, string>
	 */
	private const PLUGIN_ADDED_META = array(
		Options::META_SOURCE_POST_ID      => 'source post ID',
		Options::META_SOURCE_LINK         => 'source post URL',
		Options::META_SOURCE_SITE_URL     => 'source site URL',
		Options::META_IMPORTED_FROM       => 'plugin marker',
		Options::META_SOURCE_AUTHOR_EMAIL => 'source author email',
		Options::META_SOURCE_AUTHOR_LOGIN => 'source author login',
		'_thumbnail_id'                   => 'dest attachment ID (resolution-checked)',
	);

	/**
	 * Meta keys WordPress core may attach automatically to imported posts.
	 * Allowed when present, absence is fine. Empty for now; populate when
	 * runs reveal core defaults that need an allowlist entry (e.g. _edit_lock,
	 * _edit_last when posts are opened in the editor).
	 *
	 * @var array<string, string>
	 */
	private const WP_DEFAULT_META = array();

	/**
	 * Meta keys whose parity check is deferred to a later test phase. Allowed
	 * but not asserted; entries move into PLUGIN_ADDED_META when the matching
	 * phase ships and starts emitting them.
	 *
	 * @var array<string, string>
	 */
	private const DEFERRED_META = array(
		Options::META_SOURCE_POST_PARENT_ID => 'hierarchical post support',
	);

	/**
	 * Taxonomies whose term assignments are verified for parity. Aligned with
	 * the seeder's term_config(); extend alongside it when new taxonomies are
	 * added.
	 *
	 * @var list<string>
	 */
	private const TERM_TAXONOMIES_CHECKED = array( 'category', 'post_tag' );

	/**
	 * Attachment-post columns expected to differ between source media and the
	 * dest sideloaded attachment. Skipped during parity checks; the reason is
	 * documented for reviewers.
	 *
	 * @var array<string, string>
	 */
	private const ATTACHMENT_DIVERGENCE_REGISTRY = array(
		'ID'                => 'namespace difference (source vs dest WordPress)',
		'post_date'         => 'dest upload time; source date not propagated',
		'post_date_gmt'     => 'dest upload time; source date not propagated',
		'post_modified'     => 'dest upload time; source mtime not propagated',
		'post_modified_gmt' => 'dest upload time; source mtime not propagated',
		'guid'              => 'regenerated by dest WordPress upload path',
		'post_author'       => 'dest current user; source author not propagated',
		'post_status'       => "dest 'inherit'; source status not propagated",
		'post_parent'       => 'unattached on dest; importer leaves parent=0',
	);

	/**
	 * Attachment-post columns whose parity check is deferred. Reverse-asserted
	 * to the WordPress default in assert_attachment_deferred_columns_default()
	 * so the test fails when a future PR starts propagating one of them and
	 * forces the registry move.
	 *
	 * @var array<string, string>
	 */
	private const ATTACHMENT_DEFERRED_REGISTRY = array(
		'post_title'   => 'deferred: source media title not propagated yet',
		'post_excerpt' => 'deferred: source media caption not propagated yet',
		'post_content' => 'deferred: source media description not propagated yet',
		'post_name'    => 'deferred: filename-derived; source slug not propagated',
	);

	/**
	 * Plugin-added meta keys the importer writes on every sideloaded
	 * attachment, regardless of whether it came from inline content or the
	 * featured-image path.
	 *
	 * @var array<string, string>
	 */
	private const PLUGIN_ADDED_ATTACHMENT_META = array(
		Options::META_ORIGINAL_URL  => 'source URL the attachment was sideloaded from',
		Options::META_IMPORTED_FROM => 'source site URL',
	);

	/**
	 * Additional plugin-added meta keys written only on attachments imported
	 * via the featured-image path. Inline-imported attachments do not get
	 * these.
	 *
	 * @var array<string, string>
	 */
	private const PLUGIN_ADDED_FEATURED_ATTACHMENT_META = array(
		Options::META_FEATURED_MEDIA_ID => 'source featured-media ID for dedup lookup',
		Options::META_MEDIA_TYPE        => "'featured_image' marker on the featured path",
	);

	/**
	 * Attachment meta keys WordPress core writes on every sideloaded
	 * attachment. Their values are dest-regenerated artifacts (path, sub-size
	 * map), so they're classified rather than parity-checked.
	 *
	 * @var array<string, string>
	 */
	private const ATTACHMENT_META_DIVERGENCE = array(
		'_wp_attached_file'       => 'dest uploads-relative; source not propagated',
		'_wp_attachment_metadata' => 'regenerated by dest WordPress (sizes, paths)',
	);

	/**
	 * Attachment meta keys whose parity check is deferred. Reverse-asserted
	 * absent in assert_attachment_deferred_meta_absent() so the test fails
	 * when a future PR starts propagating them.
	 *
	 * @var array<string, string>
	 */
	private const ATTACHMENT_META_DEFERRED = array(
		'_wp_attachment_image_alt' => 'deferred: source alt_text not propagated yet',
	);

	/**
	 * Value the importer stores in META_MEDIA_TYPE for featured-image
	 * attachments, mirroring Media_Importer's literal.
	 */
	private const FEATURED_MEDIA_TYPE_VALUE = 'featured_image';

	/**
	 * Asserts parity for identity-style columns (type, slug).
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_identity_columns(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		self::assert_mapped_columns(
			self::IDENTITY_COLUMNS,
			$source_body,
			$dest_post,
			$test
		);
	}

	/**
	 * Asserts parity for content-style columns (title, excerpt).
	 *
	 * Note: post_content is intentionally NOT checked here — see
	 * CONTENT_BODY_COLUMNS and assert_content_body_parity().
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_content_columns(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		self::assert_mapped_columns(
			self::CONTENT_COLUMNS,
			$source_body,
			$dest_post,
			$test
		);
	}

	/**
	 * Asserts post_content parity via Content_Parity_Comparator: URL multisets,
	 * Gutenberg ID multisets, no source host leak, no double-encoded entities.
	 *
	 * @param array<string, mixed>  $source_body            Source REST response body.
	 * @param WP_Post               $dest_post              Imported destination post.
	 * @param array<string, string> $source_url_to_dest_url Source URL => dest URL sideload map.
	 * @param array<int, int>       $source_id_to_dest_id   Source attachment ID => dest ID.
	 * @param string                $source_base_url        Source site URL.
	 * @param TestCase              $test                   Active test case.
	 */
	public static function assert_content_body_parity(
		array $source_body,
		WP_Post $dest_post,
		array $source_url_to_dest_url,
		array $source_id_to_dest_id,
		string $source_base_url,
		TestCase $test
	): void {
		$source = (string) self::source_value( $source_body, 'content' );
		$dest   = (string) $dest_post->post_content;

		Content_Parity_Comparator::assert_url_parity(
			$source,
			$dest,
			$source_url_to_dest_url,
			$test
		);
		Content_Parity_Comparator::assert_attachment_id_parity(
			$source,
			$dest,
			$source_id_to_dest_id,
			$test
		);
		Content_Parity_Comparator::assert_no_source_host_leak(
			$dest,
			$source_base_url,
			$test
		);
		Content_Parity_Comparator::assert_no_double_encoded_entities(
			$dest,
			$test
		);
	}

	/**
	 * Asserts parity for status-style columns.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_status_columns(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		self::assert_mapped_columns(
			self::STATUS_COLUMNS,
			$source_body,
			$dest_post,
			$test
		);
	}

	/**
	 * Asserts miscellaneous column parity (menu_order) and that columns with
	 * no REST-side value land on the WordPress default on the dest.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_misc_columns(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		self::assert_mapped_columns(
			self::MISC_COLUMNS,
			$source_body,
			$dest_post,
			$test
		);

		$dest_array = $dest_post->to_array();

		foreach ( self::DEFAULT_VALUE_COLUMNS as $column => $expected ) {
			$test->assertSame(
				$expected,
				(string) ( $dest_array[ $column ] ?? '' ),
				"wp_posts column '{$column}' should be the WP default '{$expected}'"
			);
		}
	}

	/**
	 * Asserts that every wp_posts column is classified (parity rule,
	 * content-body comparator bucket, divergence registry, or deferred
	 * registry). Fails loudly when a column is unmodeled so adding columns
	 * or omitting them from the rules surfaces visibly instead of being
	 * silently skipped.
	 *
	 * @param TestCase $test Active test case.
	 */
	public static function assert_no_unmodeled_columns( TestCase $test ): void {
		$classified = array_merge(
			array_values( self::IDENTITY_COLUMNS ),
			array_values( self::CONTENT_COLUMNS ),
			array_values( self::STATUS_COLUMNS ),
			array_values( self::MISC_COLUMNS ),
			array_keys( self::DEFAULT_VALUE_COLUMNS ),
			array_keys( self::DIVERGENCE_REGISTRY ),
			array_keys( self::CONTENT_BODY_COLUMNS ),
			array_keys( self::DEFERRED_REGISTRY )
		);

		$unmodeled = array_values(
			array_diff( self::WP_POSTS_COLUMNS, $classified )
		);

		$test->assertSame(
			array(),
			$unmodeled,
			'Every wp_posts column must be classified; unmodeled columns: '
			. implode( ', ', $unmodeled )
		);
	}

	/**
	 * Asserts that every meta key in the source body's meta field
	 * round-trips to the destination post unchanged.
	 *
	 * Compares with string coercion because update_post_meta() serializes
	 * scalars as strings — int 5 becomes "5" on the way back through
	 * get_post_meta(). Array values aren't seeded yet; when they appear, this
	 * helper will need a deserialization-aware comparison.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_source_matched_meta(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		$source_meta = (array) ( $source_body['meta'] ?? array() );

		foreach ( $source_meta as $key => $value ) {
			$key        = (string) $key;
			$dest_value = get_post_meta( $dest_post->ID, $key, true );

			$test->assertSame(
				self::coerce_meta_value_for_comparison( $value ),
				self::coerce_meta_value_for_comparison( $dest_value ),
				"Meta key '{$key}' should round-trip from source to dest"
			);
		}
	}

	/**
	 * Asserts that every plugin-added meta key carries the expected value.
	 *
	 * META_SOURCE_POST_ID, META_SOURCE_LINK, META_IMPORTED_FROM, and the
	 * source-author meta values are deterministic and asserted strictly.
	 * _thumbnail_id is checked for presence + featured-attachment resolution
	 * when the source had a featured_media; absence otherwise.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_plugin_added_meta(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		$source_author = (array) ( $source_body['safe_publish_author'] ?? array() );
		$source_id     = (string) ( $source_body['id'] ?? '' );
		$source_link   = (string) ( $source_body['link'] ?? '' );
		$author_email  = (string) ( $source_author['email'] ?? '' );
		$author_login  = (string) ( $source_author['login'] ?? '' );

		$expected_site_url = '';
		if ( '' !== $source_link ) {
			$scheme = wp_parse_url( $source_link, PHP_URL_SCHEME );
			$host   = wp_parse_url( $source_link, PHP_URL_HOST );
			$port   = wp_parse_url( $source_link, PHP_URL_PORT );
			if ( is_string( $scheme ) && is_string( $host ) ) {
				$expected_site_url = $scheme . '://' . $host
					. ( is_int( $port ) ? ':' . $port : '' );
			}
		}

		$expected = array(
			Options::META_SOURCE_POST_ID      => $source_id,
			Options::META_SOURCE_LINK         => $source_link,
			Options::META_SOURCE_SITE_URL     => $expected_site_url,
			Options::META_IMPORTED_FROM       => Options::META_IMPORTED_FROM_VALUE,
			Options::META_SOURCE_AUTHOR_EMAIL => $author_email,
			Options::META_SOURCE_AUTHOR_LOGIN => $author_login,
		);

		foreach ( $expected as $key => $expected_value ) {
			$actual = (string) get_post_meta( $dest_post->ID, $key, true );
			$test->assertSame(
				$expected_value,
				$actual,
				"Plugin-added meta '{$key}' should match the expected value"
			);
		}

		self::assert_thumbnail_id_for_source(
			$source_body,
			$dest_post,
			$test
		);
	}

	/**
	 * Asserts that the dest post's _thumbnail_id meta tracks the source's
	 * featured_media: present and resolving to a featured-source attachment
	 * when the source had one, absent or 0 otherwise.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	private static function assert_thumbnail_id_for_source(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		$source_featured_id = (int) ( $source_body['featured_media'] ?? 0 );
		$thumbnail_id       = (int) get_post_meta(
			$dest_post->ID,
			'_thumbnail_id',
			true
		);

		if ( 0 === $source_featured_id ) {
			$test->assertSame(
				0,
				$thumbnail_id,
				'_thumbnail_id should be unset when source has no featured_media'
			);
			return;
		}

		$test->assertGreaterThan(
			0,
			$thumbnail_id,
			"_thumbnail_id should be set for source featured_media {$source_featured_id}"
		);

		$attachment = get_post( $thumbnail_id );
		$test->assertNotNull(
			$attachment,
			"_thumbnail_id {$thumbnail_id} should point to an existing attachment"
		);
		$test->assertSame(
			'attachment',
			$attachment->post_type,
			"_thumbnail_id {$thumbnail_id} should point to an attachment post"
		);
		$test->assertSame(
			(string) $source_featured_id,
			(string) get_post_meta(
				$thumbnail_id,
				Options::META_FEATURED_MEDIA_ID,
				true
			),
			'Featured attachment META_FEATURED_MEDIA_ID should equal source ID'
		);
	}

	/**
	 * Asserts that every meta key present on the destination post is
	 * classified: a key from the source body's meta field, a plugin-added
	 * key, an allowed WordPress default, or a deferred key reserved for a
	 * later phase. Fails loudly when an unmodeled key appears so the
	 * registries stay synced with what the import pipeline actually writes.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_no_unmodeled_meta_keys(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		$source_meta_keys = array_map(
			'strval',
			array_keys( (array) ( $source_body['meta'] ?? array() ) )
		);

		$classified = array_values(
			array_unique(
				array_merge(
					$source_meta_keys,
					array_keys( self::PLUGIN_ADDED_META ),
					array_keys( self::WP_DEFAULT_META ),
					array_keys( self::DEFERRED_META )
				)
			)
		);

		$dest_meta_keys = array_keys( (array) get_post_meta( $dest_post->ID ) );
		$unmodeled      = array_values(
			array_diff( $dest_meta_keys, $classified )
		);

		$test->assertSame(
			array(),
			$unmodeled,
			sprintf(
				'Every dest meta key on post %d must be classified;'
				. ' unmodeled: %s',
				$dest_post->ID,
				implode( ', ', $unmodeled )
			)
		);
	}

	/**
	 * Asserts that every meta key listed in DEFERRED_META is absent on the
	 * destination post. Locks the current phase's behavior so that when a
	 * later phase starts emitting one of these keys (e.g. a hierarchical-post
	 * phase emitting `META_SOURCE_POST_PARENT_ID`), the test fails and forces
	 * an explicit move out of DEFERRED_META into PLUGIN_ADDED_META.
	 *
	 * @param WP_Post  $dest_post Imported destination post.
	 * @param TestCase $test      Active test case.
	 */
	public static function assert_deferred_meta_absent(
		WP_Post $dest_post,
		TestCase $test
	): void {
		foreach ( self::DEFERRED_META as $key => $reason ) {
			$test->assertFalse(
				metadata_exists( 'post', $dest_post->ID, $key ),
				"Deferred meta '{$key}' should be absent in current phase"
				. " ({$reason}); move it to PLUGIN_ADDED_META when the"
				. ' phase that emits it ships.'
			);
		}
	}

	/**
	 * Asserts that every taxonomy assignment in the source body has a
	 * matching dest term and that the dest post is assigned to it.
	 *
	 * Source assignments come from `_embedded['wp:term']`, where each entry
	 * carries a taxonomy and a name. The importer resolves dest terms by
	 * slug (`sanitize_title( name )`) and creates the term if missing. This
	 * helper also reverse-asserts that dest terms land with parent=0 and
	 * description='' to lock in the importer's default-create behavior — a
	 * future change that propagates parent or description must update this
	 * assertion alongside the import code.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_term_assignments(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		$source_assignments = self::source_term_assignments( $source_body );

		foreach ( $source_assignments as $taxonomy => $names ) {
			foreach ( $names as $name ) {
				$slug = sanitize_title( $name );
				$term = get_term_by( 'slug', $slug, $taxonomy );

				$test->assertNotFalse(
					$term,
					"Source term '{$name}' (slug '{$slug}') should exist"
					. " on dest in taxonomy '{$taxonomy}'"
				);

				$test->assertSame(
					$name,
					(string) $term->name,
					"Dest term '{$slug}' in '{$taxonomy}' should keep its"
					. ' source name'
				);
				$test->assertSame(
					0,
					(int) $term->parent,
					"Dest term '{$slug}' in '{$taxonomy}' should have"
					. ' parent=0 (importer default)'
				);
				$test->assertSame(
					'',
					(string) $term->description,
					"Dest term '{$slug}' in '{$taxonomy}' should have"
					. ' empty description (importer default)'
				);

				$test->assertTrue(
					has_term( $term->term_id, $taxonomy, $dest_post ),
					"Dest post should be assigned term '{$slug}' in"
					. " '{$taxonomy}'"
				);
			}
		}
	}

	/**
	 * Asserts that every dest term assignment in a checked taxonomy traces
	 * back to a source assignment. Fails loudly if the importer ever attaches
	 * a term the source didn't ask for.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param WP_Post              $dest_post   Imported destination post.
	 * @param TestCase             $test        Active test case.
	 */
	public static function assert_no_unmodeled_term_assignments(
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		$source_slugs_by_taxonomy = array();
		foreach (
			self::source_term_assignments( $source_body ) as $taxonomy => $names
		) {
			foreach ( $names as $name ) {
				$source_slugs_by_taxonomy[ $taxonomy ][ sanitize_title( $name ) ]
					= true;
			}
		}

		foreach ( self::TERM_TAXONOMIES_CHECKED as $taxonomy ) {
			$dest_terms = wp_get_object_terms( $dest_post->ID, $taxonomy );
			$test->assertNotInstanceOf(
				WP_Error::class,
				$dest_terms,
				"wp_get_object_terms('{$taxonomy}') returned WP_Error;"
				. ' check TERM_TAXONOMIES_CHECKED for taxonomies that'
				. ' are registered on the test site'
			);

			foreach ( (array) $dest_terms as $term ) {
				$test->assertArrayHasKey(
					$term->slug,
					$source_slugs_by_taxonomy[ $taxonomy ] ?? array(),
					"Dest post has term '{$term->slug}' in '{$taxonomy}'"
					. ' with no matching source assignment'
				);
			}
		}
	}

	/**
	 * Reads _embedded['wp:term'] and returns a flat taxonomy => list of
	 * names map.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @return array<string, list<string>>
	 */
	private static function source_term_assignments( array $source_body ): array {
		$assignments = array();
		$embedded    = $source_body['_embedded']['wp:term'] ?? array();

		foreach ( (array) $embedded as $group ) {
			foreach ( (array) $group as $term ) {
				$taxonomy = (string) ( $term['taxonomy'] ?? '' );
				$name     = (string) ( $term['name'] ?? '' );
				if ( '' === $taxonomy || '' === $name ) {
					continue;
				}
				$assignments[ $taxonomy ][] = $name;
			}
		}

		return $assignments;
	}

	/**
	 * Coerces a meta value to a comparable representation. Scalars become
	 * strings because update_post_meta() stores them that way; arrays and
	 * objects pass through unchanged so deserialized values still compare
	 * structurally when they're seeded in a future phase.
	 *
	 * @param mixed $value Raw meta value.
	 * @return mixed
	 */
	private static function coerce_meta_value_for_comparison( mixed $value ): mixed {
		return is_scalar( $value ) ? (string) $value : $value;
	}

	/**
	 * Applies assertSame across a source-field => column mapping.
	 *
	 * Handles `[ 'raw' => string ]` REST wrappers transparently and falls
	 * back to the raw scalar when the field isn't wrapped.
	 *
	 * @param array<string, string> $mapping     Source field => wp_posts column.
	 * @param array<string, mixed>  $source_body Source REST response body.
	 * @param WP_Post               $dest_post   Imported destination post.
	 * @param TestCase              $test        Active test case.
	 */
	private static function assert_mapped_columns(
		array $mapping,
		array $source_body,
		WP_Post $dest_post,
		TestCase $test
	): void {
		$dest_array = $dest_post->to_array();

		foreach ( $mapping as $source_field => $column ) {
			$source_value = self::source_value( $source_body, $source_field );
			$dest_value   = $dest_array[ $column ] ?? null;

			$test->assertSame(
				$source_value,
				$dest_value,
				"wp_posts column '{$column}' should match source"
				. " field '{$source_field}'"
			);
		}
	}

	/**
	 * Reads a source REST body field, unwrapping [ 'raw' => ... ] wrappers.
	 *
	 * @param array<string, mixed> $source_body Source REST response body.
	 * @param string               $field       Top-level field name.
	 * @return mixed Raw field value.
	 */
	private static function source_value( array $source_body, string $field ): mixed {
		$value = $source_body[ $field ] ?? null;

		if ( is_array( $value ) && array_key_exists( 'raw', $value ) ) {
			return $value['raw'];
		}

		return $value;
	}

	/**
	 * Asserts the sideloaded attachment for a source URL passes every
	 * classification the asserter models. Returns it so callers can chain
	 * further checks.
	 *
	 * @param string   $source_url               Source URL the dest was sideloaded from.
	 * @param string   $source_site_url          Source site URL stamped on META_IMPORTED_FROM.
	 * @param string   $expected_mime_type       Expected dest post_mime_type.
	 * @param int|null $featured_source_media_id Source featured-media ID, or null for inline-only.
	 * @param TestCase $test                     Active test case.
	 * @return WP_Post Dest attachment post.
	 */
	public static function assert_imported_attachment_for_source_url(
		string $source_url,
		string $source_site_url,
		string $expected_mime_type,
		?int $featured_source_media_id,
		TestCase $test
	): WP_Post {
		$dest = self::find_dest_attachment_for_source_url( $source_url, $test );

		self::assert_attachment_parity_columns( $dest, $expected_mime_type, $test );
		self::assert_attachment_divergence_locks( $dest, $test );
		self::assert_attachment_deferred_columns_default( $dest, $test );
		self::assert_attachment_divergent_meta_present( $dest, $test );
		self::assert_attachment_deferred_meta_absent( $dest, $test );
		self::assert_attachment_plugin_meta(
			$dest,
			$source_url,
			$source_site_url,
			$featured_source_media_id,
			$test
		);
		self::assert_no_unmodeled_attachment_meta_keys(
			$dest,
			null !== $featured_source_media_id,
			$test
		);

		return $dest;
	}

	/**
	 * Asserts that every wp_posts column has a place on the attachment side:
	 * parity, divergence registry, deferred registry, or the in-method
	 * "WP defaults" bucket (columns the importer never touches on the
	 * attachment path). Mirrors assert_no_unmodeled_columns() but for
	 * attachment-specific classification.
	 *
	 * @param TestCase $test Active test case.
	 */
	public static function assert_no_unmodeled_attachment_columns(
		TestCase $test
	): void {
		// post_mime_type is the attachment-side parity column; post_type is
		// reverse-asserted to stay 'attachment' on dest in
		// assert_attachment_parity_columns().
		$classified = array_merge(
			array( 'post_mime_type', 'post_type' ),
			array_keys( self::ATTACHMENT_DIVERGENCE_REGISTRY ),
			array_keys( self::ATTACHMENT_DEFERRED_REGISTRY )
		);

		// Columns that the importer never touches on the attachment path —
		// they land on WP defaults (closed/empty/0) for every sideload and
		// aren't worth an explicit assertion. Listed here so the unmodeled
		// diff stays scoped to columns that would actually surprise a reader.
		$attachment_default_columns = array(
			'comment_status',
			'ping_status',
			'post_password',
			'to_ping',
			'pinged',
			'post_content_filtered',
			'menu_order',
			'comment_count',
		);

		$unmodeled = array_values(
			array_diff(
				self::WP_POSTS_COLUMNS,
				array_merge( $classified, $attachment_default_columns )
			)
		);

		$test->assertSame(
			array(),
			$unmodeled,
			'Every attachment column must be classified; unmodeled: '
			. implode( ', ', $unmodeled )
		);
	}

	/**
	 * Asserts the attachment-column parity rules: post_mime_type matches the
	 * expected MIME, and post_type stays 'attachment' on dest.
	 *
	 * @param WP_Post  $dest_attachment    Dest attachment post.
	 * @param string   $expected_mime_type Expected post_mime_type value.
	 * @param TestCase $test               Active test case.
	 */
	private static function assert_attachment_parity_columns(
		WP_Post $dest_attachment,
		string $expected_mime_type,
		TestCase $test
	): void {
		$test->assertSame(
			'attachment',
			$dest_attachment->post_type,
			"Dest post {$dest_attachment->ID} should be an attachment"
		);
		$test->assertSame(
			$expected_mime_type,
			$dest_attachment->post_mime_type,
			"Dest attachment {$dest_attachment->ID} should carry the source MIME"
		);
	}

	/**
	 * Reverse-asserts the ATTACHMENT_DIVERGENCE_REGISTRY locks tied to the
	 * dest current user / unattached / 'inherit' defaults.
	 *
	 * @param WP_Post  $dest_attachment Dest attachment post.
	 * @param TestCase $test            Active test case.
	 */
	private static function assert_attachment_divergence_locks(
		WP_Post $dest_attachment,
		TestCase $test
	): void {
		$test->assertSame(
			'inherit',
			$dest_attachment->post_status,
			"Dest attachment {$dest_attachment->ID} should land as 'inherit'"
		);
		$test->assertSame(
			0,
			(int) $dest_attachment->post_parent,
			"Dest attachment {$dest_attachment->ID} should be unattached"
			. ' (post_parent=0)'
		);
		$test->assertSame(
			get_current_user_id(),
			(int) $dest_attachment->post_author,
			"Dest attachment {$dest_attachment->ID} post_author should be the"
			. ' dest current user'
		);
	}

	/**
	 * Reverse-asserts each ATTACHMENT_DEFERRED_REGISTRY column lands on the
	 * WordPress default.
	 *
	 * @param WP_Post  $dest_attachment Dest attachment post.
	 * @param TestCase $test            Active test case.
	 */
	private static function assert_attachment_deferred_columns_default(
		WP_Post $dest_attachment,
		TestCase $test
	): void {
		$attached_file  = (string) get_post_meta(
			$dest_attachment->ID,
			'_wp_attached_file',
			true
		);
		$basename       = wp_basename( $attached_file );
		$expected_title = preg_replace( '/\.[^.]+$/', '', $basename );

		$test->assertSame(
			$expected_title,
			$dest_attachment->post_title,
			"Dest attachment {$dest_attachment->ID} post_title should be the"
			. ' filename-derived WP default (source title not propagated)'
		);
		$test->assertSame(
			'',
			$dest_attachment->post_excerpt,
			"Dest attachment {$dest_attachment->ID} post_excerpt should be"
			. ' empty (source caption not propagated)'
		);
		$test->assertSame(
			'',
			$dest_attachment->post_content,
			"Dest attachment {$dest_attachment->ID} post_content should be"
			. ' empty (source description not propagated)'
		);
		$test->assertNotSame(
			'',
			(string) $dest_attachment->post_name,
			"Dest attachment {$dest_attachment->ID} post_name should be the"
			. ' filename-derived WP default (source slug not propagated)'
		);
	}

	/**
	 * Asserts each ATTACHMENT_META_DIVERGENCE key is present on the dest
	 * attachment and that the sideloaded file exists on disk at the dest
	 * path. Values themselves are not compared.
	 *
	 * @param WP_Post  $dest_attachment Dest attachment post.
	 * @param TestCase $test            Active test case.
	 */
	private static function assert_attachment_divergent_meta_present(
		WP_Post $dest_attachment,
		TestCase $test
	): void {
		$attached_file = (string) get_post_meta(
			$dest_attachment->ID,
			'_wp_attached_file',
			true
		);
		$test->assertNotSame(
			'',
			$attached_file,
			"Dest attachment {$dest_attachment->ID} should have"
			. ' _wp_attached_file set'
		);

		$uploads   = wp_upload_dir();
		$full_path = trailingslashit( $uploads['basedir'] ) . $attached_file;
		$test->assertFileExists(
			$full_path,
			"Sideloaded file for attachment {$dest_attachment->ID} should"
			. " exist on disk at '{$full_path}'"
		);

		$metadata = get_post_meta(
			$dest_attachment->ID,
			'_wp_attachment_metadata',
			true
		);
		$test->assertIsArray(
			$metadata,
			"Dest attachment {$dest_attachment->ID} should have"
			. ' _wp_attachment_metadata regenerated as an array'
		);
	}

	/**
	 * Reverse-asserts each ATTACHMENT_META_DEFERRED key is absent on the dest
	 * attachment.
	 *
	 * @param WP_Post  $dest_attachment Dest attachment post.
	 * @param TestCase $test            Active test case.
	 */
	private static function assert_attachment_deferred_meta_absent(
		WP_Post $dest_attachment,
		TestCase $test
	): void {
		foreach ( self::ATTACHMENT_META_DEFERRED as $key => $reason ) {
			$test->assertFalse(
				metadata_exists( 'post', $dest_attachment->ID, $key ),
				"Deferred attachment meta '{$key}' should be absent in current"
				. " phase ({$reason})"
			);
		}
	}

	/**
	 * Asserts PLUGIN_ADDED_ATTACHMENT_META values, plus
	 * PLUGIN_ADDED_FEATURED_ATTACHMENT_META when the attachment was imported
	 * via the featured-image path.
	 *
	 * @param WP_Post  $dest_attachment          Dest attachment post.
	 * @param string   $source_url               Source URL the dest was sideloaded from.
	 * @param string   $source_site_url          Source site URL.
	 * @param int|null $featured_source_media_id Source featured-media ID, or null for inline-only.
	 * @param TestCase $test                     Active test case.
	 */
	private static function assert_attachment_plugin_meta(
		WP_Post $dest_attachment,
		string $source_url,
		string $source_site_url,
		?int $featured_source_media_id,
		TestCase $test
	): void {
		$test->assertSame(
			$source_url,
			(string) get_post_meta(
				$dest_attachment->ID,
				Options::META_ORIGINAL_URL,
				true
			),
			"Attachment {$dest_attachment->ID} META_ORIGINAL_URL should equal"
			. ' source URL'
		);
		$test->assertSame(
			$source_site_url,
			(string) get_post_meta(
				$dest_attachment->ID,
				Options::META_IMPORTED_FROM,
				true
			),
			"Attachment {$dest_attachment->ID} META_IMPORTED_FROM should equal"
			. ' source site URL'
		);

		if ( null === $featured_source_media_id ) {
			return;
		}

		$test->assertSame(
			(string) $featured_source_media_id,
			(string) get_post_meta(
				$dest_attachment->ID,
				Options::META_FEATURED_MEDIA_ID,
				true
			),
			"Attachment {$dest_attachment->ID} META_FEATURED_MEDIA_ID should"
			. " equal source ID {$featured_source_media_id}"
		);
		$test->assertSame(
			self::FEATURED_MEDIA_TYPE_VALUE,
			(string) get_post_meta(
				$dest_attachment->ID,
				Options::META_MEDIA_TYPE,
				true
			),
			"Attachment {$dest_attachment->ID} META_MEDIA_TYPE should be"
			. " '" . self::FEATURED_MEDIA_TYPE_VALUE . "'"
		);
	}

	/**
	 * Asserts that every meta key present on the dest attachment is
	 * classified: a plugin-added key, a WP-default divergent key, or a
	 * deferred key. Inline-only attachments are not allowed to carry
	 * featured-specific plugin meta; featured-sourced ones are.
	 *
	 * @param WP_Post  $dest_attachment Dest attachment post.
	 * @param bool     $is_featured     True when the attachment was imported
	 *                                  via the featured-image path.
	 * @param TestCase $test            Active test case.
	 */
	private static function assert_no_unmodeled_attachment_meta_keys(
		WP_Post $dest_attachment,
		bool $is_featured,
		TestCase $test
	): void {
		$classified = array_merge(
			array_keys( self::PLUGIN_ADDED_ATTACHMENT_META ),
			array_keys( self::ATTACHMENT_META_DIVERGENCE ),
			array_keys( self::ATTACHMENT_META_DEFERRED )
		);

		if ( $is_featured ) {
			$classified = array_merge(
				$classified,
				array_keys( self::PLUGIN_ADDED_FEATURED_ATTACHMENT_META )
			);
		}

		$dest_keys = array_keys(
			(array) get_post_meta( $dest_attachment->ID )
		);
		$unmodeled = array_values( array_diff( $dest_keys, $classified ) );

		$test->assertSame(
			array(),
			$unmodeled,
			sprintf(
				'Every dest attachment meta key on attachment %d must be'
				. ' classified; unmodeled: %s',
				$dest_attachment->ID,
				implode( ', ', $unmodeled )
			)
		);
	}

	/**
	 * Resolves the single dest attachment whose META_ORIGINAL_URL equals the
	 * given source URL. Fails the test when zero or more than one match —
	 * both states indicate the importer behaved unexpectedly (missing
	 * sideload, or a dedup miss that produced duplicates).
	 *
	 * @param string   $source_url Source URL.
	 * @param TestCase $test       Active test case.
	 * @return WP_Post Dest attachment post.
	 */
	private static function find_dest_attachment_for_source_url(
		string $source_url,
		TestCase $test
	): WP_Post {
		$attachments = get_posts(
			array(
				'post_type'        => 'attachment',
				'post_status'      => 'any',
				// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_key
				'meta_key'         => Options::META_ORIGINAL_URL,
				// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_value
				'meta_value'       => $source_url,
				'posts_per_page'   => 2,
				'suppress_filters' => false,
			)
		);

		$test->assertCount(
			1,
			$attachments,
			'Exactly one dest attachment should exist for source URL'
			. " '{$source_url}'"
		);

		return $attachments[0];
	}
}
