name: Unit tests

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: PHP tests
        if: ${{ !cancelled() }}
        run: npm run test:php

      - name: JS tests
        if: ${{ !cancelled() }}
        run: npm run test:js
