name: WordPress trunk tests

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    uses: ./.github/workflows/reusable-integration-tests.yml
    with:
      # BEGIN GENERATED COMPATIBILITY MATRIX
      php-version: '8.5'
      # END GENERATED COMPATIBILITY MATRIX
      wordpress-ref: WordPress/WordPress#master
      wordpress-version: trunk
